"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10
terms will be:
1,2,3,5,8,13,21,34,55,89,... (Where the sum of the even numbers is 44)
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sums of the even-valued
terms. (The Fibonacci sequence is F_n+1 = F_n + F_n-1)
"""

sequence = [1, 2]
total = 2

while True:
    next_number = sequence[-1] + sequence[-2]
    if next_number > 4_000_000:
        break
    
    sequence.append(next_number)
    
    if next_number % 2 == 0:
        total += next_number
        
print(total)